-- MySQL Script generated by MySQL Workbench
-- Fri Feb 12 11:49:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EmpresaRH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EmpresaRH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EmpresaRH` DEFAULT CHARACTER SET utf8 ;
USE `EmpresaRH` ;

-- -----------------------------------------------------
-- Table `EmpresaRH`.`EmpresaRH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaRH`.`EmpresaRH` (
  `idEmpresaRH` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEmpresaRH`),
  UNIQUE INDEX `idEmpresaRH_UNIQUE` (`idEmpresaRH` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmpresaRH`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmpresaRH`.`Funcionário` (
  `idFuncionário` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `EmpresaRH_idEmpresaRH` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFuncionário`, `EmpresaRH_idEmpresaRH`),
  INDEX `fk_Funcionário_EmpresaRH_idx` (`EmpresaRH_idEmpresaRH` ASC) ,
  UNIQUE INDEX `idFuncionário_UNIQUE` (`idFuncionário` ASC) ,
  CONSTRAINT `fk_Funcionário_EmpresaRH`
    FOREIGN KEY (`EmpresaRH_idEmpresaRH`)
    REFERENCES `EmpresaRH`.`EmpresaRH` (`idEmpresaRH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
